spring:
  application:
    name: client-two
server:
  port: '8200'

# to use other address
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true